-- 코드를 입력하세요
SELECT YEAR(T2.SALES_DATE) AS YEAR, MONTH(T2.SALES_DATE) AS MONTH, T1.GENDER, 
COUNT(DISTINCT T2.USER_ID) AS USERS
FROM USER_INFO T1, ONLINE_SALE T2
WHERE T1.USER_ID = T2.USER_ID
AND T1.GENDER IS NOT NULL
GROUP BY 1,2,3
ORDER BY 1,2,3;