-- 코드를 입력하세요
WITH RECURSIVE HOURS AS 
(SELECT 0 AS HOUR 
 UNION ALL 
 SELECT HOUR+1 FROM HOURS WHERE HOUR<23)
 
 SELECT HOUR, COUNT(ANIMAL_ID) AS COUNT
 FROM HOURS LEFT JOIN ANIMAL_OUTS
 ON HOUR = HOUR(ANIMAL_OUTS.DATETIME)
 GROUP BY 1
 ORDER BY 1;