-- 코드를 입력하세요
SELECT T1.CATEGORY, SUM(T2.SALES) AS TOTAL_SALES
FROM BOOK T1, BOOK_SALES T2
WHERE T1.BOOK_ID = T2.BOOK_ID
AND EXTRACT(YEAR FROM T2.SALES_DATE) = 2022
AND EXTRACT(MONTH FROM T2.SALES_DATE) = 01
GROUP BY 1
ORDER BY 1;