-- 코드를 입력하세요
SELECT T1.AUTHOR_ID, T2.AUTHOR_NAME, T1.CATEGORY, 
SUM(T3.SALES * T1.PRICE) AS TOTAL_SALES
FROM BOOK T1, AUTHOR T2, BOOK_SALES T3
WHERE T1.AUTHOR_ID = T2.AUTHOR_ID AND T1.BOOK_ID = T3.BOOK_ID
AND T3.SALES_DATE LIKE '2022-01%'
GROUP BY 1, 3
ORDER BY 1, 3 DESC;
