-- 코드를 입력하세요
SELECT T1.BOOK_ID, T2.AUTHOR_NAME, DATE_FORMAT(T1.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK T1, AUTHOR T2
WHERE T1.AUTHOR_ID = T2.AUTHOR_ID
AND T1.CATEGORY = '경제'
ORDER BY 3;